apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a8z85k5mg-java-springboot
  janus-idp.io/tekton: a8z85k5mg-java-springboot
  backstage.io/kubernetes-id: a8z85k5mg-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a8z85k5mg-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
